### ISSUE TITLE
Touche Entrée dans la créa/édition d'airplay

### ISSUE THREAD

**Issue by martinkirch** [martinkirch/disco#6]
Sur les pages de création ou d'édition de l'airplay, si je met mon curseru dans l'input du titre et que j'appuie sur la touche Entrée, ça supprime la première entrée de l'airplay!
1. ça ne doit pas faire ça
2. je m'attendais à ce que ça soumette le formulaire - ce que ça ne devrait pas faire non plus (http://stackoverflow.com/questions/2794017/disable-form-submission-via-enter-key-on-only-some-fields)

**Comment by Number6406** [comment]
- [x] fait
