### ISSUE TITLE
Création de CD - bug d'auto-complétion

### ISSUE THREAD

**Issue by martinkirch** [martinkirch/disco#7]
Sur la page de création d'un CD, les noms des artistes choisis apparaissent encore en bas de la page, en dessous de la track-list

**Comment by Number6406** [comment]
Apparement c'est pour l'accès aux handicapés. On garde ?

**Comment by martinkirch** [comment]
Non, vu tout ce qu'il y a autour ça ne les aiderait pas, de toute façon !
